import { QuartzConfig } from "../../quartz/cfg"
import {
  AddFavicons,
  AfterArticle,
  AliasRedirects,
  AllTagsPage,
  Assets,
  Bibtex,
  CrawlLinks,
  CreatedModifiedDate,
  FixFootnotes,
  FrontMatter,
  GitHubFlavoredMarkdown,
  GraphMapPage,
  HTMLFormattingImprovement,
  Latex,
  NotFoundPage,
  ObsidianFlavoredMarkdown,
  PopulateExternalMarkdown,
  RecentPostsPage,
  RemoveDrafts,
  Static,
  stripBadges,
  SyntaxHighlighting,
  TableOfContents,
  TagAcronyms,
  TagPage,
  TextFormattingImprovement,
  TroutOrnamentHr,
  Twemoji,
  WrapNakedElements,
  addAssetDimensionsFromSrc,
  ColorVariables,
  ContentIndex,
  ContentPage,
  ComponentResources,
  rehypeCustomSpoiler,
  rehypeCustomSubtitle,
  PopulateContainers,
} from "../../quartz/plugins"

const config: QuartzConfig = {
  configuration: {
    pageTitle: "Volumes",
    enablePopovers: true,
    analytics: null,

    baseUrl: "volumesredesign.pages.dev",
    ignorePatterns: ["private", "templates/**", ".obsidian"],
    defaultDateType: "published",
    navbar: {
      pages: [
        { title: "Map", slug: "/map" },
        { title: "Literature", slug: "/Literature" },
        { title: "Homelab & PC", slug: "/Homelab,-PC-and-EDC" },
        { title: "Cooking", slug: "/Cooking" },
        { title: "Health", slug: "/Health-and-biohacking" },
        { title: "Clothes", slug: "/Clothes"},
        { title: "House & Reno", slug:"/House--and--Apartment"},
        { title: "This Website", slug:"This-Website"},
      ],
    },
  },
  plugins: {
    transformers: [
      FrontMatter(),
      PopulateExternalMarkdown({
        sources: {
          punctilio: {
            owner: "alexander-turner",
            repo: "punctilio",
            transform: stripBadges,
          },
          "lint-staged": {
            filePath: "package.json",
            jsonPath: "lint-staged",
            transform: (content: string) => `\`\`\`json\n${content}\n\`\`\``,
          },
        },
      }),
      CreatedModifiedDate(),
      TextFormattingImprovement(),
      Twemoji(),
      TroutOrnamentHr(),
      Bibtex(),
      SyntaxHighlighting({
        theme: {
          light: "github-light",
          dark: "github-dark",
        },
        keepBackground: false,
      }),
      ObsidianFlavoredMarkdown({
        enableInHtmlEmbed: true,
        parseArrows: false,
        enableCheckbox: true,
      }),
      GitHubFlavoredMarkdown({ enableSmartyPants: false }),
      FixFootnotes(),
      WrapNakedElements(),
      HTMLFormattingImprovement(),
      Latex(),
      CrawlLinks({ lazyLoad: true, markdownLinkResolution: "shortest" }),
      rehypeCustomSpoiler(),
      rehypeCustomSubtitle(),
      TagAcronyms(),
      AfterArticle(),
      AddFavicons(),
      ColorVariables(),
      TableOfContents({ minEntries: 3 }),
      addAssetDimensionsFromSrc(),
    ],
    filters: [RemoveDrafts()],
    emitters: [
      AliasRedirects(),
      ComponentResources(),
      ContentPage(),
      GraphMapPage(),
      PopulateContainers(),
      TagPage(),
      AllTagsPage(),
      RecentPostsPage(),
      ContentIndex({
        enableSiteMap: true,
        enableRSS: true,
      }),
      Assets(),
      Static(),
      NotFoundPage(),
    ],
  },
}

export default config
